Changes to support web build in Play app

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -4,10 +4,15 @@
 # fail fast
 set -e
 
+NODE_VERSION=0.10.26
+GEMS="sass"
+
 BP_DIR=$(cd $(dirname $0)/..; pwd) # absolute path
 BIN_DIR=$BP_DIR/bin
 OPT_DIR=$BP_DIR/opt
 . $BIN_DIR/common
+. $BIN_DIR/common-node
+. $BIN_DIR/common-ruby
 
 # parse args
 APP_BUILD_DIR=$(cd $1; pwd)
@@ -18,7 +23,7 @@ ENV_DIR=$3
 BUILD_DIR="/tmp/scala_buildpack_build_dir"
 mv $APP_BUILD_DIR $BUILD_DIR
 
-curl --silent --location http://heroku-jvm-common.s3.amazonaws.com/jvm-buildpack-common.tar.gz | tar xzm
+curl --silent --location http://heroku-jvm-common.s3.amazonaws.com/jvm-buildpack-common.tar.gz | tar xz
 . bin/util
 . bin/java
 
@@ -27,12 +32,12 @@ export_env_dir $ENV_DIR
 #create the cache dir if it doesn't exist
 mkdir -p $CACHE_DIR
 
-# create default system.properties
+# create default system.properties 
 if [ ! -f ${BUILD_DIR}/system.properties ]; then
   echo "java.runtime.version=1.6" > ${BUILD_DIR}/system.properties
 fi
 
-# install JDK
+# install JDK 
 javaVersion=$(detect_java_version ${BUILD_DIR})
 echo -n "-----> Installing OpenJDK ${javaVersion}..."
 install_java ${BUILD_DIR} ${javaVersion}
@@ -51,28 +56,53 @@ SBT_BINDIR="$SBT_USER_HOME"/bin
 # chdir as sbt expects
 cd $BUILD_DIR
 
+install_gems $CACHE_DIR $GEMS
+
+# Download node from Heroku's S3 mirror of nodejs.org/dist
+status "Downloading and installing node"
+node_url="http://s3pository.heroku.com/node/v$NODE_VERSION/node-v$NODE_VERSION-linux-x64.tar.gz"
+curl $node_url -s -o - | tar xzf - -C $BUILD_DIR
+
+# Move node (and npm) into ./vendor and make them executable
+mkdir -p $BUILD_DIR/vendor
+mv $BUILD_DIR/node-v$NODE_VERSION-linux-x64 $BUILD_DIR/vendor/node
+chmod +x $BUILD_DIR/vendor/node/bin/*
+PATH=$BUILD_DIR/vendor/node/bin:$PATH
+
+# Run subsequent node/npm commands from the build path
+npm install -g bower
+npm install -g grunt-cli
+gem install sass
+
+cd public
+source update-js.sh
+grunt release
+cd ../
+
 # unpack cache
-CACHED_DIRS="$SBT_USER_HOME/.ivy2 $SBT_USER_HOME/boot $SBT_BINDIR target project/target project/boot"
+CACHED_DIRS="$SBT_USER_HOME/.ivy2 $SBT_BINDIR target project/target project/boot"
 for DIR in $CACHED_DIRS; do
   cache_copy $DIR $CACHE_DIR $BUILD_DIR
 done
 
 # these are preliminary checks. actual version check happens below when attempting to download sbt boot.properties
 if ! test -e project/build.properties; then
-	echo " !      Error, your scala project must include project/build.properties and define sbt.version"
-	echo " !      You must use a release verison of sbt, sbt.version=0.11.0 or greater"
+    echo " !      Error, your scala project must include project/build.properties and define sbt.version"
+    echo " !      You must use a release verison of sbt, sbt.version=0.11.0 or greater"
         exit 1
 fi
 
 if ! has_supported_sbt_version ${BUILD_DIR}; then
-	echo " !      Error, you have defined an unsupported sbt.version in project/build.properties"
-	echo " !      You must use a release verison of sbt, sbt.version=0.11.0 or greater"
-	exit 1
+    echo " !      Error, you have defined an unsupported sbt.version in project/build.properties"
+    echo " !      You must use a release verison of sbt, sbt.version=0.11.0 or greater"
+    exit 1
 fi
-
+ 
 SBT_VERSION="$(get_supported_sbt_version ${BUILD_DIR})"
 SBT_JAR="sbt-launch.jar"
-SBT_URL="http://typesafe.artifactoryonline.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.5/$SBT_JAR"
+SBT_PROPS="sbt-$SBT_VERSION.boot.properties"
+SBT_URL="http://typesafe.artifactoryonline.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.1/$SBT_JAR"
+SBT_PROPS_URL="http://s3.amazonaws.com/heroku-jvm-langpack-scala/$SBT_PROPS"
 ## in 0.10 start-script will depend on package, if packaging
 ## is required - it may not be, we can run .class files or a package-war
 ## instead.
@@ -99,24 +129,26 @@ if [ ! -f "$SBT_BINDIR"/"$SBT_JAR" ]; then
   curl --silent --max-time 60 -O --location $SBT_URL --fail || error "Failed to download $SBT_JAR"
   echo "done"
 
+  echo "#!/usr/bin/env bash" > sbt
+  echo "java -Dsbt.boot.properties=/app/.sbt_home/bin/sbt.boot.properties  -Duser.home=/app/.sbt_home -Divy.default.ivy.user.dir=/app/.sbt_home/.ivy2 -jar /app/.sbt_home/bin/$SBT_JAR \"\$@\"" >> sbt
+  chmod a+x sbt
+
   cd $BUILD_DIR
 fi
 
-# Install the custom sbt script for cmds like `heroku run sbt console`
-cp -p $OPT_DIR/sbt-launcher.sh $SBT_BINDIR/sbt
-chmod a+x $SBT_BINDIR/sbt
-
-# download and cache the dependencies if this is the first build
-if [ ! -d "$SBT_USER_HOME/.ivy2" ]; then
-  if is_sbt_native_packager $BUILD_DIR || is_play $BUILD_DIR; then
-    prime_ivy_cache "$BUILD_DIR" "$SBT_USER_HOME_ABSOLUTE" "$SBT_BINDIR/$SBT_JAR"
-    run_sbt "$SBT_USER_HOME_ABSOLUTE" "$SBT_BINDIR/$SBT_JAR" "update"
-    cache_copy $SBT_USER_HOME/.ivy2 $BUILD_DIR $CACHE_DIR
-  fi
-fi
+# copy in heroku sbt plugin
+HEROKU_PLUGIN="HerokuPlugin.scala"
+mkdir -p "$SBT_USER_HOME/.sbt/plugins"
+cp -p $OPT_DIR/$HEROKU_PLUGIN $SBT_USER_HOME/.sbt/plugins/$HEROKU_PLUGIN
 
 # build app
-run_sbt "$SBT_USER_HOME_ABSOLUTE" "$SBT_BINDIR/$SBT_JAR" "$SBT_TASKS"
+echo "-----> Running: sbt $SBT_TASKS"
+test -e "$SBT_BINDIR"/sbt.boot.properties && PROPS_OPTION="-Dsbt.boot.properties=$SBT_BINDIR/sbt.boot.properties"
+HOME="$SBT_USER_HOME_ABSOLUTE" java -Xms768M -Xmx1024M -XX:MaxPermSize=512M -XX:+CMSClassUnloadingEnabled -Dfile.encoding=UTF8 -Duser.home="$SBT_USER_HOME_ABSOLUTE" -Dsbt.log.noformat=true -Divy.default.ivy.user.dir="$SBT_USER_HOME_ABSOLUTE/.ivy2" -Dsbt.global.base="$SBT_USER_HOME_ABSOLUTE" -jar "$SBT_BINDIR"/$SBT_JAR $SBT_TASKS 2>&1 | sed -u 's/^/       /'
+if [ "${PIPESTATUS[*]}" != "0 0" ]; then
+  echo " !     Failed to build app with sbt"
+  exit 1
+fi
 
 PROFILE_PATH="$BUILD_DIR/.profile.d/scala.sh"
 mkdir -p $(dirname $PROFILE_PATH)
@@ -128,23 +160,46 @@ for DIR in $CACHED_DIRS; do
   cache_copy $DIR $BUILD_DIR $CACHE_DIR
 done
 
-# drop useless directories from slug for play and sbt-native-launcher only
-if is_sbt_native_packager $BUILD_DIR || is_play $BUILD_DIR; then
-  if [ -d $SBT_USER_HOME/.ivy2 ]; then
-    echo "-----> Dropping ivy cache from the slug"
-    rm -rf $SBT_USER_HOME/.ivy2
-  fi
-  if [ -d $BUILD_DIR/project/boot ] ; then
-    echo "-----> Dropping project boot dir from the slug"
-    rm -rf $BUILD_DIR/project/boot
-  fi
-  if [ -d $BUILD_DIR/target ] ; then
-    echo "-----> Dropping compilation artifacts from the slug"
-    rm -rf $BUILD_DIR/target/scala-*
-    rm -rf $BUILD_DIR/target/streams
-    rm -rf $BUILD_DIR/target/resolution-cache
-  fi
-fi
+# drop useless directories from slug for play
+echo "-----> Dropping node_modules and bower_components"
+cd public
+rm -rf node_modules
+cd app
+rm -rf node_modules
+rm -rf bower_components
+cd ../consent
+rm -rf node_modules
+rm -rf bower_components
+cd ../shared
+rm -rf node_modules
+rm -rf bower_components
+cd ../neurod
+rm -rf node_modules
+rm -rf bower_components
+cd ../../
+
+echo "-----> Dropping vendor"
+rm -rf vendor
+
+echo "-----> Dropping tests"
+rm -rf test
+
+echo "-----> Dropping docs"
+rm -rf target/universal/stage/share/doc
+
+echo "-----> Dropping phantomdriver log"
+rm -f phantomjsdriver.log
+
+echo "-----> Dropping ivy cache from the slug"
+rm -rf $SBT_USER_HOME/.ivy2
+
+echo "-----> Dropping project boot dir from the slug"
+rm -rf $BUILD_DIR/project/boot
+
+echo "-----> Dropping compilation artifacts from the slug"
+rm -rf $BUILD_DIR/target/scala-*
+rm -rf $BUILD_DIR/target/streams
+rm -rf $BUILD_DIR/target/resolution-cache
 
 # Move compiled app back to where Heroku expects it
 mv $BUILD_DIR $APP_BUILD_DIR
